# Generated by Django 4.0.2 on 2022-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='File',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='books',
            name='Image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
