# Generated by Django 4.0.2 on 2022-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_books_file_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
